project_id: '555103'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: src/features/i18n/resources/en/*.json
    translation: src/features/i18n/resources/%two_letters_code%/%original_file_name%
