trigger:
  branches:
    include:
      - master
variables:
  - group: Mobile # change it to the name you have set

pool:
  vmImage: 'macos-latest'
steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '18.16.1' # you can use your desired version here
  - script: yarn install
    displayName: Install Dependencies
  - task: Gradle@2
    displayName: 'Build APK'
    inputs:
      gradleWrapperFile: 'android/gradlew'
      workingDirectory: 'android/'
      tasks: 'assembleRelease'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish APK to artifacts'
    inputs:
      PathtoPublish: 'android/app/build/outputs/apk/release'
      ArtifactName: 'android'
      publishLocation: 'Container'
  - task: CocoaPods@0
    displayName: 'Install CocoaPods'
    inputs:
      workingDirectory: 'ios'
  - task: Xcode@5
    displayName: 'Build Release App'
    inputs:
      actions: 'build'
      configuration: 'Release'
      sdk: 'iphonesimulator'
      xcWorkspacePath: 'ios/NucleusUiPatternExamples.xcworkspace'
      scheme: 'NucleusUiPatternExamples'
      packageApp: true
      exportPath: 'output'
  - task: CopyFiles@2
    displayName: 'Copy App'
    inputs:
      contents: '**/*.app/**'
      targetFolder: '$(build.artifactStagingDirectory)'
      overWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish APP to artifacts'
    inputs:
      PathtoPublish: '$(build.artifactStagingDirectory)'
      ArtifactName: 'ios'
      publishLocation: 'Container'