name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  renovate:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Self-hosted Renovate
        env:
          LOG_LEVEL: "debug"
          LANG: "en_US:UTF-8"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
        run: npx renovate
